// Generated by CoffeeScript 1.7.1
(function() {
  window.game = new Phaser.Game(400, 490, Phaser.AUTO, 'game');

  window.score = 0;

  game.state.add('load', window.load_state);

  game.state.add('menu', window.menu_state);

  game.state.add('play', window.play_state);

  game.state.start('load');

}).call(this);
