// Generated by CoffeeScript 1.7.1
(function() {
  window.load_state = {
    preload: function() {
      game.stage.backgroundColor = '#71c5cf';
      game.load.image('bird', 'assets/bird.png');
      game.load.image('pipe', 'assets/pipe.png');
      game.load.audio('jump', 'assets/jump.wav');
    },
    create: function() {
      game.state.start('menu');
    }
  };

}).call(this);
