// Generated by CoffeeScript 1.7.1
(function() {
  window.menu_state = {
    create: function() {
      var scoreLabel, spaceKey, style, text, x, y;
      spaceKey = game.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);
      spaceKey.onDown.add(this.start, this);
      style = {
        font: "30px Arial",
        fill: "#ffffff"
      };
      x = game.world.width / 2;
      y = game.world.height / 2;
      text = game.add.text(x, y - 50, "Press space to start", style);
      text.anchor.setTo(0.5, 0.5);
      if (window.score > 0) {
        scoreLabel = game.add.text(x, y + 50, "score: " + window.score, style);
        scoreLabel.anchor.setTo(0.5, 0.5);
      }
    },
    start: function() {
      game.input.keyboard.removeKey(Phaser.Keyboard.SPACEBAR);
      game.state.start('play');
    }
  };

}).call(this);
